services:
    db:
        image: postgres:latest
        container_name: my_postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase

    redis:
        image: redis:latest
        container_name: my_redis
        ports:
            - "6379:6379"
